import { Ic } from './icons.jsx';

export const TRIP_ROLES=[
  {id:"cook",       label:"Cook",         icon:Ic.food},
  {id:"fireStarter",label:"Fire Starter", icon:Ic.flame},
  {id:"firstAid",   label:"First Aid",    icon:Ic.shield},
  {id:"navigation", label:"Navigation",   icon:Ic.nav},
];

export const WIDGET_DEFS=[
  {id:"miles",    label:"Miles",     icon:Ic.foot,   get:(t)=>((t.trails||[]).reduce((a,x)=>a+(+x.miles||0),0)).toFixed(1)},
  {id:"meals",    label:"Meals",     icon:Ic.food,   get:(t)=>(t.meals||[]).length},
  {id:"cost",     label:"Food Cost", icon:Ic.dollar, get:(t)=>`$${((t.meals||[]).reduce((a,m)=>a+(+m.cost||0),0)).toFixed(0)}`},
  {id:"crew",     label:"Crew",      icon:Ic.users,  get:(t)=>(t.members||[]).length},
  {id:"days",     label:"Days",      icon:Ic.cal,    get:(t)=>t.start&&t.end?Math.round((new Date(t.end+"T00:00")-new Date(t.start+"T00:00"))/86400000)+1:"—"},
  {id:"nights",   label:"Nights",    icon:Ic.tent,   get:(t)=>t.start&&t.end?Math.round((new Date(t.end+"T00:00")-new Date(t.start+"T00:00"))/86400000):"—"},
  {id:"waypoints",label:"Waypoints", icon:Ic.pin,    get:(t)=>(t.waypoints||[]).length},
  {id:"trails",   label:"Trails",    icon:Ic.mtn,    get:(t)=>(t.trails||[]).length},
  {id:"events",   label:"Events",    icon:Ic.cal,    get:(t)=>(t.events||[]).length},
  {id:"photos",   label:"Photos",    icon:Ic.img,    get:(t)=>(t.photos||[]).length},
];
export const DEFAULT_WIDGETS=["miles","meals","cost","crew"];

export const St={
  app:{minHeight:"100dvh",background:"var(--night)",color:"var(--paper)",position:"relative",overflowX:"hidden"},
  contours:{position:"fixed",inset:0,width:"100%",height:"100%",opacity:.05,pointerEvents:"none",zIndex:0},
  main:{maxWidth:760,margin:"0 auto",padding:"0 18px 90px",position:"relative",zIndex:1,isolation:"isolate"},

  header:{position:"sticky",top:0,zIndex:20,maxWidth:760,margin:"0 auto",
    padding:"calc(env(safe-area-inset-top) + 14px) 18px 12px",
    display:"flex",alignItems:"center",justifyContent:"space-between",gap:12,
    background:"linear-gradient(var(--night) 72%, transparent)"},
  logoMark:{width:40,height:40,borderRadius:11,background:"var(--ember)",display:"grid",placeItems:"center",flexShrink:0},
  brand:{fontFamily:"'Oswald',sans-serif",fontWeight:700,fontSize:22,letterSpacing:1,lineHeight:1},
  tagline:{fontSize:10,letterSpacing:2.5,textTransform:"uppercase",color:"var(--sage)",marginTop:3},
  profileBtn:{display:"flex",alignItems:"center",gap:8,background:"var(--pine)",border:"1px solid var(--line)",borderRadius:12,padding:"6px 10px",cursor:"pointer"},
  modeDot:{width:8,height:8,borderRadius:8,flexShrink:0},
  avatarSm:{width:26,height:26,borderRadius:8,background:"var(--mist)",display:"grid",placeItems:"center",fontFamily:"'Oswald',sans-serif",fontWeight:700,color:"var(--paper)",fontSize:13},
  linkBtn:{background:"none",border:"none",color:"var(--ember2)",cursor:"pointer",fontWeight:600,fontSize:13,padding:0,textDecoration:"underline"},
  localBanner:{marginTop:18,padding:"10px 12px",background:"rgba(232,178,60,.08)",border:"1px solid rgba(232,178,60,.25)",borderRadius:10,fontSize:11.5,color:"var(--sage)",display:"flex",gap:8,alignItems:"flex-start",lineHeight:1.5},

  sectionHead:{display:"flex",alignItems:"flex-end",justifyContent:"space-between",gap:12,margin:"20px 0 18px",flexWrap:"wrap"},
  h1:{fontFamily:"'Oswald',sans-serif",fontSize:30,fontWeight:600,margin:0,letterSpacing:.5},
  h2:{fontFamily:"'Oswald',sans-serif",fontSize:19,fontWeight:600,margin:"0 0 12px",letterSpacing:.5},
  sub:{color:"var(--sage)",fontSize:13,margin:"4px 0 0",lineHeight:1.5},
  hintSm:{color:"var(--sage)",fontSize:11.5,marginTop:8,lineHeight:1.5,opacity:.85},
  miniLabel:{fontSize:11,color:"var(--sage)",textTransform:"uppercase",letterSpacing:1,fontWeight:600},

  mapHead:{display:"flex",alignItems:"center",gap:7,fontFamily:"'Oswald',sans-serif",fontSize:14,fontWeight:600,letterSpacing:.5,marginBottom:10},
  mapHome:{height:200,borderRadius:14,overflow:"hidden",border:"1px solid var(--line)"},

  yearLabel:{display:"flex",alignItems:"center",gap:12,marginBottom:14},
  yearNum:{fontFamily:"'Oswald',sans-serif",fontSize:14,fontWeight:700,color:"var(--ember2)",letterSpacing:2},
  yearLine:{flex:1,height:1,background:"var(--line)"},

  tripGrid:{display:"grid",gridTemplateColumns:"repeat(auto-fill,minmax(230px,1fr))",gap:14},
  card:{position:"relative",textAlign:"left",background:"var(--pine)",border:"1px solid var(--line)",borderRadius:16,overflow:"hidden",cursor:"pointer",color:"var(--paper)",padding:0,display:"flex",flexDirection:"column"},
  card2:{background:"var(--pine)",border:"1px solid var(--line)",borderRadius:18},
  cardCover:{height:120,background:"var(--moss) center/cover",display:"grid",placeItems:"center",position:"relative",backgroundSize:"cover",backgroundPosition:"center"},
  coverGrad:{position:"absolute",inset:0,background:"linear-gradient(to top,var(--pine),transparent 60%)"},
  cardDate:{position:"absolute",top:10,left:10,background:"rgba(15,26,23,.82)",color:"var(--paper)",fontSize:11,fontWeight:600,padding:"3px 9px",borderRadius:8,fontFamily:"'Oswald',sans-serif",letterSpacing:.5},
  cardBody:{padding:"12px 14px 14px"},
  cardTitle:{fontFamily:"'Oswald',sans-serif",fontSize:17,fontWeight:600,lineHeight:1.15},
  cardLoc:{display:"flex",alignItems:"center",gap:4,color:"var(--sage)",fontSize:12,margin:"5px 0 10px"},
  cardStats:{display:"flex",gap:12,fontSize:12,opacity:.85,alignItems:"center"},
  cardArrow:{position:"absolute",right:12,bottom:14,color:"var(--mist)"},

  tripWrap:{position:"fixed",inset:0,display:"flex",flexDirection:"column",background:"var(--night)",zIndex:10},
  tripScroll:{flex:1,overflowY:"auto",WebkitOverflowScrolling:"touch",maxWidth:760,margin:"0 auto",width:"100%",
    padding:"0 18px",paddingTop:"calc(env(safe-area-inset-top) + 12px)"},
  tripBody:{paddingBottom:32},
  backBtn:{display:"inline-flex",alignItems:"center",gap:6,background:"none",border:"none",color:"var(--sage)",cursor:"pointer",fontSize:13,padding:"6px 0 10px",fontWeight:500},
  detailHero:{height:170,borderRadius:18,background:"var(--moss) center/cover",position:"relative",display:"flex",alignItems:"flex-end",overflow:"hidden",backgroundSize:"cover",backgroundPosition:"center",marginBottom:18},
  heroGrad:{position:"absolute",inset:0,background:"linear-gradient(to top,var(--night) 5%,transparent 70%)"},
  heroInner:{position:"relative",padding:"18px 20px",width:"100%"},
  heroDates:{display:"inline-flex",alignItems:"center",gap:6,color:"var(--gold)",fontSize:12,fontWeight:600,marginBottom:6},
  heroTitle:{fontFamily:"'Oswald',sans-serif",fontSize:26,fontWeight:700,margin:0,letterSpacing:.5},
  heroLoc:{display:"flex",alignItems:"center",gap:5,opacity:.85,fontSize:13,marginTop:4},

  tabBarBottom:{display:"flex",justifyContent:"space-around",alignItems:"center",
    background:"rgba(15,26,23,0.97)",backdropFilter:"blur(16px)",WebkitBackdropFilter:"blur(16px)",
    borderTop:"1px solid var(--line)",
    padding:"6px 6px calc(env(safe-area-inset-bottom) + 6px)",flexShrink:0,overflow:"visible",position:"relative"},
  bottomTab:{flex:1,display:"flex",flexDirection:"column",alignItems:"center",gap:3,background:"none",border:"none",
    color:"var(--sage)",cursor:"pointer",padding:"6px 4px",borderRadius:12},
  bottomTabOn:{color:"var(--ember2)"},
  bottomTabLabel:{fontSize:10.5,fontWeight:600,letterSpacing:.3},
  centerBtn:{width:56,height:56,borderRadius:28,background:"var(--ember)",border:"2px solid rgba(232,104,44,0.25)",
    color:"var(--paper)",cursor:"pointer",display:"flex",alignItems:"center",justifyContent:"center",
    boxShadow:"0 4px 18px rgba(232,104,44,0.45),0 2px 6px rgba(0,0,0,0.3)",marginTop:-18,
    transition:"background .15s,transform .15s,box-shadow .15s",flexShrink:0},
  centerBtnOpen:{background:"var(--ember2)",transform:"scale(1.06)",boxShadow:"0 6px 22px rgba(242,148,78,0.5),0 2px 6px rgba(0,0,0,0.3)"},
  centerMenuItem:{display:"flex",flexDirection:"row",alignItems:"center",gap:10,
    background:"rgba(22,42,36,0.97)",border:"1px solid var(--line)",color:"var(--sage)",cursor:"pointer",
    padding:"11px 16px",borderRadius:10,fontSize:13,fontWeight:600,whiteSpace:"nowrap",
    backdropFilter:"blur(16px)",WebkitBackdropFilter:"blur(16px)"},
  centerMenuItemOn:{color:"var(--ember2)",background:"rgba(242,148,78,0.08)"},

  pane:{},
  statRow:{display:"grid",gridTemplateColumns:"1fr 1fr 1fr 1fr",gap:10,marginBottom:14},
  statCard:{background:"var(--pine)",border:"1px solid var(--line)",borderRadius:13,padding:"14px 12px",textAlign:"center"},
  statValue:{fontFamily:"'Oswald',sans-serif",fontSize:24,fontWeight:700,margin:"6px 0 2px"},
  statLabel:{fontSize:11,color:"var(--sage)",textTransform:"uppercase",letterSpacing:.5},

  block:{background:"var(--pine)",border:"1px solid var(--line)",borderRadius:14,padding:16,marginBottom:14},
  blockHead:{display:"flex",justifyContent:"space-between",alignItems:"center",fontFamily:"'Oswald',sans-serif",fontSize:14,fontWeight:600,marginBottom:10,letterSpacing:.5},
  readyTrack:{height:8,background:"var(--moss)",borderRadius:6,overflow:"hidden"},
  readyFill:{height:"100%",background:"linear-gradient(90deg,var(--ember),var(--gold))",transition:"width .4s"},
  taskRow:{display:"flex",alignItems:"center",gap:10,fontSize:13.5},
  taskDot:{width:18,height:18,borderRadius:5,border:"1.5px solid var(--line)",display:"grid",placeItems:"center",flexShrink:0},
  notes:{width:"100%",minHeight:88,background:"var(--night)",border:"1px solid var(--line)",borderRadius:10,color:"var(--paper)",padding:12,fontSize:13.5,resize:"vertical",lineHeight:1.5},

  shareCard:{display:"flex",justifyContent:"space-between",alignItems:"center",gap:12,background:"linear-gradient(135deg,var(--moss),var(--pine))",border:"1px solid var(--line)",borderRadius:14,padding:"14px 16px",marginBottom:14},
  shareLabel:{fontSize:11,color:"var(--sage)",textTransform:"uppercase",letterSpacing:1},
  shareCode:{fontFamily:"'Oswald',sans-serif",fontSize:26,fontWeight:700,letterSpacing:5,color:"var(--gold)",margin:"2px 0"},
  iconChip:{width:40,height:40,borderRadius:10,background:"var(--night)",border:"1px solid var(--line)",color:"var(--sage)",display:"grid",placeItems:"center",cursor:"pointer"},

  listHead:{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:12,gap:10,flexWrap:"wrap"},
  itemRow:{display:"flex",alignItems:"center",gap:12,background:"var(--pine)",border:"1px solid var(--line)",borderRadius:12,padding:"12px 14px"},
  itemTitle:{fontSize:14.5,fontWeight:600},
  itemMeta:{fontSize:12,color:"var(--sage)",marginTop:2},
  dayChip:{fontFamily:"'Oswald',sans-serif",fontSize:12,fontWeight:700,color:"var(--ember2)",background:"rgba(232,104,44,.12)",padding:"5px 9px",borderRadius:8,minWidth:42,textAlign:"center"},
  avatar:{width:38,height:38,borderRadius:10,background:"var(--mist)",display:"grid",placeItems:"center",fontFamily:"'Oswald',sans-serif",fontWeight:700,color:"var(--paper)",fontSize:16,flexShrink:0},
  checkBtn:{width:24,height:24,borderRadius:7,border:"1.5px solid var(--mist)",background:"none",cursor:"pointer",display:"grid",placeItems:"center",flexShrink:0},
  checkOn:{background:"var(--ember)",borderColor:"var(--ember)"},
  navBtn:{width:34,height:34,borderRadius:9,background:"var(--moss)",display:"grid",placeItems:"center",color:"var(--sage)",textDecoration:"none",flexShrink:0},
  netPill:{fontSize:12,fontWeight:600,padding:"5px 10px",borderRadius:8,whiteSpace:"nowrap"},
  dirBtn:{display:"inline-flex",alignItems:"center",gap:6,background:"var(--moss)",color:"var(--paper)",border:"1px solid var(--line)",borderRadius:10,padding:"9px 13px",fontSize:13,fontWeight:600,textDecoration:"none"},

  memberCard:{background:"var(--pine)",border:"1px solid var(--line)",borderRadius:14,padding:14},
  memberAvatarImg:{width:38,height:38,borderRadius:10,objectFit:"cover",flexShrink:0},
  memberMeta:{fontSize:12,color:"var(--sage)",margin:"8px 0 2px"},
  memberRow:{display:"flex",alignItems:"center",gap:8,marginTop:8,fontSize:13},
  youTag:{fontSize:10,background:"var(--moss)",color:"var(--sage)",padding:"1px 6px",borderRadius:6,marginLeft:6,fontWeight:600,verticalAlign:"middle"},
  ownerBadge:{fontSize:10,background:"rgba(232,178,60,.18)",color:"var(--gold)",padding:"1px 6px",borderRadius:6,marginLeft:6,fontWeight:600,verticalAlign:"middle"},
  inlineInput:{flex:1,background:"var(--night)",border:"1px solid var(--line)",borderRadius:8,color:"var(--paper)",padding:"7px 10px",fontSize:13},
  uploadChip:{display:"inline-flex",alignItems:"center",gap:4,background:"var(--moss)",color:"var(--paper)",borderRadius:8,padding:"5px 10px",fontSize:12,fontWeight:600,cursor:"pointer"},
  photoStrip:{display:"flex",gap:8,overflowX:"auto",marginTop:8,paddingBottom:4},
  photoThumb:{position:"relative",flexShrink:0},
  photoImg:{width:72,height:72,borderRadius:10,objectFit:"cover",display:"block"},
  photoDel:{position:"absolute",top:4,right:4,width:20,height:20,borderRadius:6,background:"rgba(15,26,23,.8)",border:"none",color:"var(--paper)",display:"grid",placeItems:"center",cursor:"pointer"},
  coverPreview:{width:"100%",height:140,objectFit:"cover",borderRadius:10,display:"block"},

  mealCard:{background:"var(--pine)",border:"1px solid var(--line)",borderRadius:14,padding:14},
  expandRow:{display:"flex",alignItems:"center",gap:7,width:"100%",background:"var(--night)",border:"1px solid var(--line)",borderRadius:10,padding:"9px 12px",color:"var(--sage)",fontSize:12.5,cursor:"pointer",marginTop:10},
  itemsBox:{marginTop:10,display:"grid",gap:6},
  shopRow:{display:"flex",alignItems:"center",gap:10},
  shopMeal:{fontSize:11,color:"var(--sage)",background:"var(--moss)",padding:"2px 8px",borderRadius:6},
  shopBringer:{fontSize:11,color:"var(--gold)",background:"rgba(232,178,60,.12)",padding:"2px 8px",borderRadius:6,whiteSpace:"nowrap"},
  itemRespSelect:{background:"var(--moss)",border:"1px solid var(--line)",borderRadius:7,color:"var(--paper)",fontSize:11,padding:"3px 6px",cursor:"pointer",maxWidth:76},

  empty:{display:"flex",flexDirection:"column",alignItems:"center",gap:10,textAlign:"center",color:"var(--sage)",fontSize:13,padding:"28px 20px",border:"1px dashed var(--line)",borderRadius:14,marginBottom:14,lineHeight:1.5},
  mapBig:{height:300,borderRadius:12,overflow:"hidden",border:"1px solid var(--line)"},
  mapPick:{height:360,borderRadius:12,overflow:"hidden",border:"1px solid var(--line)",marginBottom:14},

  primaryBtn:{display:"inline-flex",alignItems:"center",gap:6,background:"var(--ember)",color:"var(--night)",border:"none",borderRadius:11,padding:"10px 16px",fontSize:14,fontWeight:600,cursor:"pointer"},
  ghostBtn:{background:"none",border:"1px solid var(--line)",color:"var(--sage)",borderRadius:11,padding:"10px 16px",fontSize:14,cursor:"pointer",fontWeight:500},
  smallBtn:{display:"inline-flex",alignItems:"center",gap:5,background:"var(--moss)",color:"var(--paper)",border:"none",borderRadius:10,padding:"9px 13px",fontSize:13,fontWeight:600,cursor:"pointer"},
  dangerBtn:{display:"inline-flex",alignItems:"center",gap:6,background:"none",border:"1px solid rgba(217,83,79,.4)",color:"#E78A87",borderRadius:11,padding:"10px 16px",fontSize:13.5,fontWeight:600,cursor:"pointer"},
  iconBtn:{background:"none",border:"none",color:"var(--mist)",cursor:"pointer",display:"grid",placeItems:"center",padding:4},

  overlay:{position:"fixed",inset:0,background:"rgba(8,14,12,.72)",backdropFilter:"blur(3px)",display:"grid",placeItems:"center",zIndex:9999,padding:18},
  modal:{width:"100%",maxWidth:440,background:"var(--pine)",border:"1px solid var(--line)",borderRadius:18,padding:20,maxHeight:"90vh",overflowY:"auto"},
  modalHead:{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:16},
  modalTitle:{fontFamily:"'Oswald',sans-serif",fontSize:20,fontWeight:600,letterSpacing:.5},
  modalActions:{display:"flex",gap:10,justifyContent:"flex-end",marginTop:6},
  fieldLabel:{fontSize:12,color:"var(--sage)",marginBottom:6,fontWeight:500},
  input:{width:"100%",background:"var(--night)",border:"1px solid var(--line)",borderRadius:10,color:"var(--paper)",padding:"10px 12px",fontSize:14},
  toggle:{display:"inline-flex",alignItems:"center",gap:8,background:"var(--night)",border:"1px solid var(--line)",borderRadius:10,padding:"8px 12px",color:"var(--sage)",cursor:"pointer",fontSize:13,fontWeight:600},
  toggleOn:{color:"var(--paper)"},
  toggleKnob:{width:16,height:16,borderRadius:5,background:"var(--mist)",transition:"all .2s"},
  toggleKnobOn:{background:"var(--ember)"},

  modeBadge:{display:"inline-flex",alignItems:"center",gap:5,fontSize:11.5,fontWeight:600,padding:"4px 9px",borderRadius:8},
  ol:{margin:"4px 0 0",paddingLeft:18,color:"var(--paper)",fontSize:13.5,lineHeight:1.7},
  errText:{color:"#E78A87",fontSize:12.5,marginTop:4,marginBottom:4},

  galleryGrid:{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:5,marginTop:4},

  chatContainer:{display:"flex",flexDirection:"column",height:"100%",minHeight:400},
  messagesBox:{flex:1,overflowY:"auto",WebkitOverflowScrolling:"touch",display:"flex",flexDirection:"column",gap:8,padding:"12px 0",marginBottom:12},
  messageRow:{display:"flex",gap:10,alignItems:"flex-start"},
  messageBubble:{background:"var(--moss)",borderRadius:12,padding:"10px 14px",maxWidth:"85%"},
  messageMeta:{fontSize:12,color:"var(--sage)",marginTop:4},
  messageText:{fontSize:13.5,lineHeight:1.5,wordBreak:"break-word"},
  inputBox:{display:"flex",gap:8,alignItems:"flex-end",padding:"12px 0",borderTop:"1px solid var(--line)"},
  messageInput:{flex:1,background:"var(--night)",border:"1px solid var(--line)",borderRadius:10,color:"var(--paper)",padding:"10px 12px",fontSize:13.5,resize:"none",minHeight:40,maxHeight:100},

  toast:{position:"fixed",bottom:"calc(env(safe-area-inset-bottom) + 90px)",left:"50%",transform:"translateX(-50%)",
    background:"var(--pine)",border:"1px solid var(--ember)",borderRadius:12,padding:"11px 18px",fontSize:13.5,fontWeight:600,
    display:"flex",alignItems:"center",gap:8,zIndex:60,boxShadow:"0 8px 30px rgba(0,0,0,.4)"},
};
